import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import CreateTwo from "../components/createtwo";
import Head from 'next/head';
import styles from '../styles/Home.module.css';
//import { loadComponents } from 'next/dist/server/load-components';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anon Stars</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CreateTwo />
      </main>
      <footer className={styles.footer}>
      </footer>
    </div>
  );
};

export default Home;
