import type { NextPage } from 'next';
import ViewProfile from "../components/viewProfile";
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { ethers, BigNumber, Contract } from 'ethers';
import { contractAddresses, abiFile, apiKey, BadgesABI } from "../constants";
import { Badges } from "../components/BadgesType"; // Link at the end of the tutorial

const provider = new ethers.providers.InfuraProvider(137, apiKey[137])

// Badges contract address on Polygon Playground
const badgesContractAddress = "0x71a7089C56DFf528f330Bc0116C0917cd05B51Fc"

const badgesContract = new Contract(
                                badgesContractAddress, 
                                BadgesABI, 
                                provider 
                    ) as Badges;
                    
const aliceAddress = "0xF61CabBa1e6FC166A66bcA0fcaa83762EdB6D4Bd";

// token id of the Ethereum Power User badge
const EthereumPowerUserTokenId = 10000005; 

// query the balance of Alice
//const balance = await badgesContract.balanceOf(aliceAddress, EthereumPowerUserTokenId);
//console.log(balance);
//const balance = await badgesContract.balanceOf(aliceAddress, EthereumPowerUserTokenId);

// check if the balance of Alice is greater than zero


// query the balance of Alice
const balance = async () => {
    const balance = await badgesContract.balanceOf(aliceAddress, EthereumPowerUserTokenId);
    console.log(balance);
    return balance;
};

console.log(balance);

/*
if (balance.gt(0)) { 
    console.log("You have the Ethereum Power User badge, well done!") 
} else { 
    console.log("You don't have the Ethereum Power User badge.") 
}
*/

const Home: NextPage = () => {
    return (
      <div className={styles.container}>
        <Head>
          <title>Anon Stars</title>
          <meta
            name="description"
            content="Generated by @rainbow-me/create-rainbowkit"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <ViewProfile />
        </main>
        <footer className={styles.footer}>
        </footer>
      </div>
    );
  };
  
  export default Home;